apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-env
  labels:
    {{- include "hello-env.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-env
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "hello-env.labels" . | nindent 8 }}
    spec:
      containers:
        - name: hello-env
          image: "nginx:1.27-alpine"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: html
          configMap:
            name: hello-env-html
