apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    {{- include "n-tier-app.componentLabels" (dict "component" "api" "Chart" .Chart "Release" .Release) | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "n-tier-app.componentLabels" (dict "component" "api" "Chart" .Chart "Release" .Release) | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: api
          image: "{{ .Values.imageRegistry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: PGHOST
              value: postgres
            - name: PGDATABASE
              valueFrom:
                secretKeyRef: { name: postgres-credentials, key: POSTGRES_DB }
            - name: PGUSER
              valueFrom:
                secretKeyRef: { name: postgres-credentials, key: POSTGRES_USER }
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef: { name: postgres-credentials, key: POSTGRES_PASSWORD }
            - name: REDIS_HOST
              value: redis
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 3000 }
            initialDelaySeconds: 15
            periodSeconds: 10
