apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "n-tier-app.componentLabels" (dict "component" "redis" "Chart" .Chart "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "n-tier-app.componentLabels" (dict "component" "redis" "Chart" .Chart "Release" .Release) | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10
